language: php

sudo: false

php:
  - 5.2
  - 5.3
  # - 5.4
  # - 5.5
  - 5.6
  - 7.0
  # - 7.1
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash tests/bin/install.sh wordpress_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

script:
  - phpunit -c phpunit.xml.dist
  - bash tests/bin/travis.sh during

after_script:
  - bash tests/bin/travis.sh after

notifications:
 slack: givewp:AgWxvdTjTkSjd8FHM5ndeSH5